export const sustainabilityClubQuestions = [
    "What inspired you to join our sustainability club?",
    "What are your passions and interests within the realm of sustainability?",
    "How do you envision our club contributing to local or global environmental efforts?",
    "What personal experiences have shaped your perspective on environmentalism?",
    "How can we leverage our collective knowledge and skills to make a meaningful impact?",
    "What are some of the most influential environmental documentaries or books you've encountered?",
    "How do you stay informed about current environmental issues and trends?",
    "What are your favorite sustainable practices that you implement in your daily life?",
    "How can we promote inclusivity and diversity within our club and the broader sustainability movement?",
    "What are some of the challenges you've faced in your sustainability journey and how did you overcome them?",
    "How can we collaborate with other organizations or individuals to amplify our impact?",
    "What are some creative ways we can engage the community in our mission?",
    "How can we foster a sense of community and support among our members?",
    "What is your favorite aspect of being part of this sustainability club?",
    "How can we create a welcoming and supportive environment for all members?",
    "What are your aspirations for your involvement with environmental activism?",
    "How can we measure the effectiveness of our initiatives and make necessary adjustments?",
    "What role do you believe technology plays in advancing sustainability?",
    "How can we bridge the gap between environmental awareness and action?",
    "What are your thoughts on the importance of individual responsibility in combating climate change?",
    "How can we promote sustainable habits in our university and beyond?",
    "What are some innovative solutions you've heard of or want to explore for addressing environmental challenges?",
    "How can we ensure that our club remains relevant and adaptable to evolving environmental concerns?",
    "What are your hopes for the future of the sustainability movement?",
    "How can we make sustainability more accessible and equitable for all communities?",
    "What are some ethical considerations we should keep in mind in our sustainability efforts?",
    "How can we foster a culture of curiosity and lifelong learning within our club?",
    "What are your favorite ways to connect with nature and appreciate the environment?",
    "How can we use storytelling and art to raise awareness about sustainability issues?",
    "What are some inspiring examples of how individuals or organizations have made a significant impact on the environment?",
    "How can we create a legacy that will continue to promote sustainability long after our time?",
    "What are some of the most pressing environmental challenges facing our generation and how can we address them?",
    "How can we balance environmental concerns with economic and social needs?",
    "What are your thoughts on the role of policy and advocacy in promoting sustainability?",
    "How can we use our collective voices to influence positive change?",
    "What are some of the most effective ways to engage the younger generation in sustainability efforts?",
    "How can we incorporate cultural perspectives and traditional knowledge into our understanding of sustainability?",
    "What are your favorite sustainable products or services that you recommend?"
];
